### ISSUE TITLE
Can’t select database

### ISSUE THREAD

**Issue by kumo** [mhoofman/wordpress-heroku#25]
I cloned the project, followed the configuration and pushed it to heroku, but when I try to access wp-admin it tells me that it can access the server ("which means your username and password is okay") but it cannot select the database. Is there something that I need to do to get it to work?

**Comment by jiang925** [comment]
Check this blog out. It fixes the "Can't select database problem on WordPress on Heroku".

http://blog.jiang925.com/2015/06/01/run-heroku-version-of-wordpress-locally-on-raspberry-pi-fixed-cant-select-database-problem/
